<!doctype html>
<html lang="en">
<head>
    <base href="${request.contextPath}/">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Base Admin 后台管理系统脚手架</title>
    <link rel="stylesheet" href="lib/layui/css/layui.css">
    <link rel="stylesheet" href="css/error.css">
</head>
<body>
    <div class="layui-container">
        <p class="error">500</p>
    </div>
</body>
</html>